### ISSUE TITLE
Unstable notification and crashing.

### ISSUE THREAD

**Issue by Gamusren** [arminghofrani/chalkboard#2]
I am using Samsung so Android Oreo. I want to keep the software in background so when I get to school I can know schedule instantly, however, even if I turned off the background restrictions on app and turn on the notification in app, the notification can not last long and it's very unstable. Also, sometimes when I clicked into the app, the current class remaining time is not refreshed, I have to force stop and reopen it to display properly. Last issue is, this app always crash in background. Please fix these three issues!

**Comment by AlanZhangYao** [comment]
Typo.. Samsung s9

**Comment by arminghofrani** [comment]
Hello. All of these issues are happening because Google made some changes from Android 7 to Android 8 (Oreo) which are affecting the way the app behaves. I'm currently working on an update for this. The app should be updated in the next few days.

**Comment by arminghofrani** [comment]
Fixed.
